"""Generate the Python↔TypeScript schedule-engine conformance fixture.

The Python engine (wakeup-scheduler.py) is the source of truth. This script
evaluates it on a fixed, seeded corpus and writes the answers to
src/backend/claude-session/__fixtures__/schedule-conformance.json; the
TypeScript port's conformance test must reproduce every answer.

    python3 substrate/scripts/tests/schedule_conformance_gen.py          # rewrite
    python3 substrate/scripts/tests/schedule_conformance_gen.py --check  # exit 1 if stale

Regenerate whenever the engine changes.
"""

import json
import os
import random
import sys
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import test_schedule_engine as T  # noqa: E402  (shares the loader, tables, generator)

eng = T.eng
OUT = os.path.join(HERE, "..", "..", "..", "src", "backend", "claude-session", "__fixtures__",
                   "schedule-conformance.json")

JUNK = ["", "09:00", "9:00", "24:00", "09:60", "٠٩:٠٠", 0, 1, -1, 2, 2.0, 2.5, 31, 32,
        True, False, None, "last", "first", "mon", "Monday", "Funday", [], ["mon"], ["mon", "xyz"],
        ["09:00", "09:00"], ["09:00", "17:00"], {"from": "09:00", "to": "17:00"},
        {"from": "09:00", "to": "09:00"}, "2027-01-01", "2027-02-30", "2027-01-01T00:00:00Z",
        "2027-01-01T25:00:00", "2027-01-01T00:00:00+05:30", "11mo", "0mo", "15", 15, "1.5h", "02-29",
        "08-03", "America/New_York", "america/new_york", "Mars/Olympus", "UTC"]
FIELDS = ["type", "at", "every", "day", "days", "date", "nth", "weekday", "window", "start", "until",
          "count", "timezone"]


def verdicts(r):
    cases = [{"schedule": s, "valid": True} for s in T.VALID]
    cases += [{"schedule": s, "valid": False} for s, _ in T.INVALID]
    base = datetime(2027, 1, 1)
    for _ in range(1500):
        sch = T.rand_schedule(r, base)
        for _ in range(r.randint(1, 2)):
            field = r.choice(FIELDS)
            if r.random() < 0.15:
                sch.pop(field, None)
            else:
                sch[field] = r.choice(JUNK) if field != "type" else r.choice(
                    ["interval", "daily", "weekly", "monthly", "yearly", "one_shot", "hourly"])
        cases.append({"schedule": sch, "valid": eng.schedule_error(sch) is None})
    return cases


def next_cases(r):
    base = datetime(2027, 1, 1)
    trans = {z: T.transitions(ZoneInfo(z), 2027) for z in T.ZONES}
    out = []
    hand = [
        ({"type": "interval", "every": "11mo", "start": "2026-09-03T09:00:00-04:00"}, T.ny(2026, 10, 11, 14)),
        ({"type": "daily", "at": "02:30", "timezone": "America/New_York"}, T.ny(2027, 3, 13, 12)),
        ({"type": "daily", "at": "01:30", "timezone": "America/New_York"}, T.ny(2027, 11, 6, 12)),
        ({"type": "monthly", "day": 31, "at": "09:00", "timezone": "America/New_York"}, T.ny(2027, 1, 31, 9)),
        ({"type": "monthly", "nth": "last", "weekday": "fri", "at": "16:00",
          "timezone": "America/New_York"}, T.ny(2027, 1, 1)),
        ({"type": "interval", "every": "4h", "window": {"from": "02:15", "to": "03:30"},
          "timezone": "America/New_York"}, T.ny(2027, 3, 13, 22)),
    ]
    for sch, after in hand:
        out.append(case(sch, after, "America/New_York", steps=6))
    while len(out) < 1200:
        sch = T.rand_schedule(r, base)
        if eng.schedule_error(sch):
            continue
        box = r.choice(T.ZONES)
        tz_trans = trans[sch.get("timezone") or box]
        if tz_trans and r.random() < 0.5:
            after = float(r.choice(tz_trans) + r.randint(-36 * 3600, 36 * 3600))
        else:
            after = (base + timedelta(days=r.randint(-200, 600))).replace(tzinfo=timezone.utc).timestamp()
            after += r.randrange(86400)
        if r.random() < 0.3:
            after += round(r.random(), 3)
        out.append(case(sch, after, box, steps=4))
    return out


def case(sch, after, box, steps):
    zone = ZoneInfo(box)
    expected = []
    t = after
    for _ in range(steps):
        n = eng.next_fire(sch, t, zone)
        expected.append(n)
        if n is None:
            break
        t = n
    return {"schedule": sch, "after": after, "boxZone": box, "expected": expected}


def build():
    r = random.Random(77001)
    return {
        "note": "GENERATED by substrate/scripts/tests/schedule_conformance_gen.py from the Python "
                "schedule engine. Do not edit; regenerate.",
        "validation": verdicts(r),
        "next": next_cases(r),
    }


def main():
    data = json.dumps(build(), indent=1, sort_keys=True, ensure_ascii=False) + "\n"
    if "--check" in sys.argv:
        try:
            current = open(OUT, encoding="utf-8").read()
        except FileNotFoundError:
            current = ""
        if current != data:
            print("schedule-conformance.json is stale — run "
                  "python3 substrate/scripts/tests/schedule_conformance_gen.py", file=sys.stderr)
            sys.exit(1)
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(data)
    print("wrote %s" % os.path.normpath(OUT))


if __name__ == "__main__":
    main()
