services:
  skynet:
    image: ghcr.io/lukegus/skynet:latest
    container_name: skynet
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - skynet-data:/app/data
    environment:
      PORT: "8080"
      GUACD_HOST: "guacd"
    depends_on:
      - guacd
    networks:
      - skynet-net

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    networks:
      - skynet-net

volumes:
  skynet-data:
    driver: local

networks:
  skynet-net:
    driver: bridge
