/**
 * TypeScript port of the schedule engine in substrate/scripts/wakeup-scheduler.py
 * (the section headed "Schedule engine"). The Python file is the source of
 * truth — it decides when things actually fire. This port exists so the app
 * can show "Next: in 27m" and validate specs before writing them.
 *
 * Held to the Python engine by a conformance fixture
 * (`__fixtures__/schedule-conformance.json`, generated by
 * substrate/scripts/tests/schedule_conformance_gen.py from the Python engine
 * itself): every case's validation verdict and next-fire instant must match
 * exactly. Change both sides together and regenerate the fixture.
 *
 * Function names mirror the Python ones so the two can be read side by side.
 * Wall-clock math runs in the spec's `timezone`, else `boxZone` (default: this
 * process's zone — approximate for specs that live on another box).
 */

type Schedule = Record<string, unknown>;
type HM = [number, number];
type Ymd = { y: number; m: number; d: number };

const DOW_NAMES = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"] as const;
const REPEATING_TYPES = ["interval", "daily", "weekly", "monthly", "yearly"];
const HHMM_RE = /^([0-9]{1,2}):([0-9]{2})$/;
const EVERY_RE = /^([0-9]+)(mo|s|m|h|d)?$/;
const ISO_RE =
  /^([0-9]{4})-([0-9]{2})-([0-9]{2})(?:[T ]([0-9]{2}):([0-9]{2})(?::([0-9]{2})(?:\.[0-9]+)?)?)?(Z|[+-][0-9]{2}:[0-9]{2})?$/;
const MMDD_RE = /^([0-9]{2})-([0-9]{2})$/;
const UNIT_SECS: Record<string, number> = { s: 1, m: 60, h: 3600, d: 86400 };
const MAX_CANDIDATE_DATES: Record<string, number> = { daily: 10, weekly: 4, monthly: 400, yearly: 400 };
const MAX_GRID_STEPS = 4000;
const DAY = 86400;

// ---------------------------------------------------------------------------
// Time zones
// ---------------------------------------------------------------------------

const fmtCache = new Map<string, Intl.DateTimeFormat>();

function formatter(zone: string): Intl.DateTimeFormat {
  let f = fmtCache.get(zone);
  if (!f) {
    f = new Intl.DateTimeFormat("en-US", {
      timeZone: zone,
      hourCycle: "h23",
      year: "numeric",
      month: "numeric",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
      second: "numeric",
    });
    fmtCache.set(zone, f);
  }
  return f;
}

/** Validate an IANA zone name the way Python's ZoneInfo does: it must exist,
 *  and (ZoneInfo being case-sensitive) must not be a mis-cased canonical name. */
export function isKnownZone(name: string): boolean {
  if (name.length === 0) return false;
  try {
    const resolved = new Intl.DateTimeFormat("en-US", { timeZone: name }).resolvedOptions().timeZone;
    return !(resolved.toLowerCase() === name.toLowerCase() && resolved !== name);
  } catch {
    return false;
  }
}

export function localZone(): string {
  return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
}

type Wall = { y: number; m: number; d: number; hh: number; mm: number; ss: number; frac: number };

/** Local reading of instant `ts` (epoch seconds) in `zone`. */
function toWall(ts: number, zone: string): Wall {
  const whole = Math.floor(ts);
  const parts = formatter(zone).formatToParts(new Date(whole * 1000));
  const get = (t: string) => Number(parts.find((p) => p.type === t)?.value);
  return { y: get("year"), m: get("month"), d: get("day"), hh: get("hour"), mm: get("minute"), ss: get("second"), frac: ts - whole };
}

/** The local reading as a "naive epoch": seconds as if the wall clock were UTC. */
function naiveOf(w: Wall): number {
  return Date.UTC(w.y, w.m - 1, w.d, w.hh, w.mm, w.ss) / 1000 + w.frac;
}

function naiveAt(ts: number, zone: string): number {
  return naiveOf(toWall(ts, zone));
}

function offsetAt(ts: number, zone: string): number {
  const whole = Math.floor(ts);
  return naiveAt(whole, zone) - whole;
}

/** First instant at which the local clock in `zone` reads `naive` (a naive
 *  epoch) or later — Python `_wall_ts`. Ambiguous → first occurrence; skipped
 *  by a jump → the jump instant. */
function wallTs(naive: number, zone: string): number {
  const offsets = new Set([offsetAt(naive - DAY, zone), offsetAt(naive + DAY, zone), offsetAt(naive, zone)]);
  const valid: number[] = [];
  for (const o of offsets) {
    const c = naive - o;
    if (offsetAt(c, zone) === o) valid.push(c);
  }
  if (valid.length > 0) return Math.min(...valid);
  // Gap: bisect whole seconds for the first instant whose reading is >= naive.
  const os = [...offsets];
  let lo = Math.floor(naive - Math.max(...os));
  let hi = Math.ceil(naive - Math.min(...os));
  while (lo < hi) {
    const mid = Math.floor((lo + hi) / 2);
    if (naiveAt(mid, zone) >= naive) hi = mid;
    else lo = mid + 1;
  }
  return lo;
}

function fromWall(d: Ymd, h: number, mi: number, zone: string): number {
  return wallTs(Date.UTC(d.y, d.m - 1, d.d, h, mi, 0) / 1000, zone);
}

// ---------------------------------------------------------------------------
// Calendar helpers (pure date arithmetic, no zones)
// ---------------------------------------------------------------------------

function dayNumber(d: Ymd): number {
  return Date.UTC(d.y, d.m - 1, d.d) / 1000 / DAY;
}

function fromDayNumber(n: number): Ymd {
  const t = new Date(n * DAY * 1000);
  return { y: t.getUTCFullYear(), m: t.getUTCMonth() + 1, d: t.getUTCDate() };
}

function addDays(d: Ymd, n: number): Ymd {
  return fromDayNumber(dayNumber(d) + n);
}

/** Monday = 0 … Sunday = 6 (Python date.weekday()). 1970-01-01 was a Thursday. */
function weekday(d: Ymd): number {
  return (((dayNumber(d) + 3) % 7) + 7) % 7;
}

function daysInMonth(y: number, m: number): number {
  return new Date(Date.UTC(y, m, 0)).getUTCDate();
}

function cmpYmd(a: Ymd, b: Ymd): number {
  return dayNumber(a) - dayNumber(b);
}

function wallDate(ts: number, zone: string): Ymd {
  const w = toWall(ts, zone);
  return { y: w.y, m: w.m, d: w.d };
}

/** Calendar-month add on a naive epoch, clamping the day (Python `_add_months`). */
function addMonthsNaive(naive: number, n: number): number {
  const t = new Date(Math.floor(naive) * 1000);
  const frac = naive - Math.floor(naive);
  const total = t.getUTCMonth() + n;
  const y = t.getUTCFullYear() + Math.floor(total / 12);
  const m = (total % 12) + 1;
  const d = Math.min(t.getUTCDate(), daysInMonth(y, m));
  return Date.UTC(y, m - 1, d, t.getUTCHours(), t.getUTCMinutes(), t.getUTCSeconds()) / 1000 + frac;
}

// ---------------------------------------------------------------------------
// Parsers (each mirrors the Python `_parse_*` of the same name)
// ---------------------------------------------------------------------------

function asInt(v: unknown): number | null {
  return typeof v === "number" && Number.isInteger(v) ? v : null;
}

function parseHhmm(v: unknown): HM | null {
  if (typeof v !== "string") return null;
  const m = HHMM_RE.exec(v.trim());
  if (!m) return null;
  const h = Number(m[1]);
  const mi = Number(m[2]);
  if (h > 23 || mi > 59) return null;
  return [h, mi];
}

function parseTimes(at: unknown): HM[] | null {
  const vals = Array.isArray(at) ? at : [at];
  if (vals.length === 0 || vals.length > 24) return null;
  const out: HM[] = [];
  for (const v of vals) {
    const t = parseHhmm(v);
    if (!t) return null;
    out.push(t);
  }
  if (new Set(out.map(([h, mi]) => h * 60 + mi)).size !== out.length) return null;
  return out.sort((a, b) => a[0] * 60 + a[1] - (b[0] * 60 + b[1]));
}

type Every = ["s", number] | ["mo", number];

function parseEvery(every: unknown): Every | null {
  if (typeof every === "number") {
    const n = asInt(every);
    return n !== null && n > 0 ? ["s", n * 60] : null;
  }
  if (typeof every !== "string") return null;
  const m = EVERY_RE.exec(every.trim().toLowerCase());
  if (!m || Number(m[1]) <= 0) return null;
  const n = Number(m[1]);
  const unit = m[2] ?? "m";
  if (unit === "mo") return ["mo", n];
  return ["s", n * UNIT_SECS[unit]];
}

function parseIso(v: unknown, zone: string): number | null {
  if (typeof v !== "string") return null;
  const m = ISO_RE.exec(v.trim());
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]);
  const d = Number(m[3]);
  const h = Number(m[4] ?? 0);
  const mi = Number(m[5] ?? 0);
  const sec = Number(m[6] ?? 0);
  const off = m[7];
  if (h > 23 || mi > 59 || sec > 59) return null;
  if (y < 1 || mo < 1 || mo > 12 || d < 1 || d > daysInMonth(y, mo)) return null;
  const naive = Date.UTC(y, mo - 1, d, h, mi, sec) / 1000;
  if (off === undefined) return wallTs(naive, zone);
  if (off === "Z") return naive;
  const oh = Number(off.slice(1, 3));
  const om = Number(off.slice(4, 6));
  if (oh > 23 || om > 59) return null;
  const sign = off[0] === "+" ? 1 : -1;
  return naive - sign * (oh * 3600 + om * 60);
}

/** Set of weekday ints, null = no gate, false = malformed. */
function parseDays(days: unknown): Set<number> | null | false {
  if (days === undefined || days === null || (Array.isArray(days) && days.length === 0)) return null;
  if (!Array.isArray(days)) return false;
  const out = new Set<number>();
  for (const d of days) {
    if (typeof d !== "string") return false;
    const i = (DOW_NAMES as readonly string[]).indexOf(d.trim().toLowerCase().slice(0, 3));
    if (i < 0) return false;
    out.add(i);
  }
  return out;
}

function parseWeekday(v: unknown): number | null {
  if (typeof v !== "string") return null;
  const i = (DOW_NAMES as readonly string[]).indexOf(v.trim().toLowerCase().slice(0, 3));
  return i < 0 ? null : i;
}

type Window = [number, number];

function parseWindow(w: unknown): Window | null {
  if (typeof w !== "object" || w === null || Array.isArray(w)) return null;
  const o = w as Record<string, unknown>;
  const a = parseHhmm(o.from);
  const b = parseHhmm(o.to);
  if (!a || !b || (a[0] === b[0] && a[1] === b[1])) return null;
  return [a[0] * 3600 + a[1] * 60, b[0] * 3600 + b[1] * 60];
}

function parsePositiveInt(v: unknown): number | null {
  const n = asInt(v);
  return n !== null && n >= 1 ? n : null;
}

function parseMonthDay(v: unknown): number | "last" | null {
  if (v === "last") return "last";
  const n = asInt(v);
  return n !== null && n >= 1 && n <= 31 ? n : null;
}

function parseNth(v: unknown): number | "last" | null {
  if (v === "last") return "last";
  const n = asInt(v);
  return n !== null && n >= 1 && n <= 4 ? n : null;
}

function parseYearlyDate(v: unknown): [number, number] | null {
  if (typeof v !== "string") return null;
  const m = MMDD_RE.exec(v.trim());
  if (!m) return null;
  const mo = Number(m[1]);
  const d = Number(m[2]);
  if (mo === 2 && d === 29) return null;
  if (mo < 1 || mo > 12 || d < 1 || d > daysInMonth(2001, mo)) return null;
  return [mo, d];
}

const present = (v: unknown) => v !== undefined && v !== null;

// ---------------------------------------------------------------------------
// Validation — Python `schedule_error`
// ---------------------------------------------------------------------------

export function scheduleError(sch: unknown): string | null {
  if (typeof sch !== "object" || sch === null || Array.isArray(sch)) return "`schedule` must be an object";
  const s = sch as Schedule;
  const t = s.type;
  if (t === "one_shot") {
    for (const k of ["start", "until", "count", "window", "every"]) {
      if (present(s[k])) return `one_shot: \`${k}\` is not supported`;
    }
    return null;
  }
  if (typeof t !== "string" || !REPEATING_TYPES.includes(t)) return `unknown schedule type ${JSON.stringify(t)}`;
  let zone = "UTC";
  if (present(s.timezone)) {
    if (!isKnownZone(String(s.timezone))) return `unknown IANA timezone ${JSON.stringify(s.timezone)}`;
    zone = String(s.timezone);
  }
  if (parseDays(s.days) === false) return "`days` must be a list of weekdays (mon..sun)";
  let start: number | null = null;
  let until: number | null = null;
  if (present(s.start)) {
    start = parseIso(s.start, zone);
    if (start === null) return `\`start\` ${JSON.stringify(s.start)} is not an ISO date/datetime`;
  }
  if (present(s.until)) {
    until = parseIso(s.until, zone);
    if (until === null) return `\`until\` ${JSON.stringify(s.until)} is not an ISO date/datetime`;
  }
  if (start !== null && until !== null && until < start) return "`until` is before `start`";
  if (present(s.count) && parsePositiveInt(s.count) === null) return "`count` must be a whole number ≥ 1";
  if (t !== "interval" && present(s.window)) return "`window` only applies to interval schedules";
  if (t !== "monthly" && (present(s.nth) || present(s.weekday))) return "`nth`/`weekday` only apply to monthly schedules";

  if (t === "interval") {
    if (parseEvery(s.every) === null) return `interval: \`every\` ${JSON.stringify(s.every)} must be like 30s, 15m, 2h, 1d or 11mo`;
    if (present(s.window) && parseWindow(s.window) === null) {
      return 'interval: `window` must be {"from": "HH:MM", "to": "HH:MM"} with from ≠ to';
    }
    return null;
  }
  if (parseTimes(s.at) === null) return `${t}: \`at\` must be "HH:MM" or a list of up to 24 distinct "HH:MM"`;
  if ((t === "daily" || t === "yearly") && present(s.every)) return `${t}: \`every\` is not supported`;
  if (t === "daily") return null;
  if (t === "yearly") {
    if (parseYearlyDate(s.date) === null) {
      return `yearly: \`date\` must be a real MM-DD (02-29 is not supported), got ${JSON.stringify(s.date)}`;
    }
    return null;
  }
  if (present(s.every)) {
    const n = parsePositiveInt(s.every);
    if (n === null) return `${t}: \`every\` must be a whole number ≥ 1`;
    if (n > 1 && start === null) return `${t}: \`every\` > 1 needs a \`start\` to count from`;
  }
  if (t === "weekly") {
    if (parseWeekday(s.day) === null) return `weekly: \`day\` must be mon..sun, got ${JSON.stringify(s.day)}`;
    return null;
  }
  const hasDay = present(s.day);
  const hasNth = present(s.nth) || present(s.weekday);
  if (hasDay === hasNth) return "monthly: give either `day` or `nth` + `weekday`";
  if (hasDay) {
    if (parseMonthDay(s.day) === null) return `monthly: \`day\` must be 1..31 or "last", got ${JSON.stringify(s.day)}`;
    return null;
  }
  if (parseNth(s.nth) === null) return `monthly: \`nth\` must be 1..4 or "last", got ${JSON.stringify(s.nth)}`;
  if (parseWeekday(s.weekday) === null) return `monthly: \`weekday\` must be mon..sun, got ${JSON.stringify(s.weekday)}`;
  return null;
}

// ---------------------------------------------------------------------------
// Next fire — Python `next_fire` and helpers
// ---------------------------------------------------------------------------

function monthlyDate(y: number, mo: number, s: Schedule): Ymd {
  const mdays = daysInMonth(y, mo);
  if (present(s.day)) {
    const day = parseMonthDay(s.day)!;
    return { y, m: mo, d: day === "last" ? mdays : Math.min(day, mdays) };
  }
  const wd = parseWeekday(s.weekday)!;
  const nth = parseNth(s.nth)!;
  if (nth === "last") {
    return { y, m: mo, d: mdays - ((((weekday({ y, m: mo, d: mdays }) - wd) % 7) + 7) % 7) };
  }
  const first = 1 + ((((wd - weekday({ y, m: mo, d: 1 })) % 7) + 7) % 7);
  return { y, m: mo, d: first + 7 * (nth - 1) };
}

const mod = (a: number, n: number) => ((a % n) + n) % n;

function* candidateDates(s: Schedule, d0: Ymd, startDate: Ymd | null): Generator<Ymd> {
  const t = s.type;
  if (t === "daily") {
    for (let d = d0; ; d = addDays(d, 1)) yield d;
  } else if (t === "weekly") {
    const wd = parseWeekday(s.day)!;
    const n = parsePositiveInt(s.every) ?? 1;
    let d = addDays(d0, mod(wd - weekday(d0), 7));
    const week0 = startDate ? addDays(startDate, -weekday(startDate)) : null;
    for (;;) {
      if (n === 1 || mod(Math.floor((dayNumber(d) - dayNumber(week0!)) / 7), n) === 0) yield d;
      d = addDays(d, 7);
    }
  } else if (t === "monthly") {
    const n = parsePositiveInt(s.every) ?? 1;
    let y = d0.y;
    let mo = d0.m;
    for (;;) {
      if (n === 1 || mod(y * 12 + mo - (startDate!.y * 12 + startDate!.m), n) === 0) yield monthlyDate(y, mo, s);
      if (mo === 12) {
        y += 1;
        mo = 1;
      } else mo += 1;
    }
  } else {
    const [mo, dd] = parseYearlyDate(s.date)!;
    for (let y = d0.y; ; y++) yield { y, m: mo, d: dd };
  }
}

function nextWall(
  s: Schedule,
  after: number,
  zone: string,
  start: number | null,
  until: number | null,
  days: Set<number> | null,
): number | null {
  const times = parseTimes(s.at)!;
  const floorTs = start === null ? after : Math.max(after, start - 1);
  const d0 = addDays(wallDate(floorTs, zone), -1);
  const startDate = start !== null ? wallDate(start, zone) : null;
  const cap = MAX_CANDIDATE_DATES[s.type as string];
  let seen = 0;
  for (const d of candidateDates(s, d0, startDate)) {
    if (cmpYmd(d, d0) < 0) continue;
    seen += 1;
    if (seen > cap) return null;
    if (days !== null && !days.has(weekday(d))) continue;
    let best: number | null = null;
    for (const [h, mi] of times) {
      const ts = fromWall(d, h, mi, zone);
      if (ts <= after || (start !== null && ts < start)) continue;
      if (best === null || ts < best) best = ts;
    }
    if (best === null) continue;
    if (until !== null && best > until) return null;
    return best;
  }
  return null;
}

function inWindow(sod: number, w: Window | null): boolean {
  if (w === null) return true;
  const [a, b] = w;
  return a < b ? a <= sod && sod <= b : sod >= a || sod <= b;
}

function allowed(ts: number, zone: string, days: Set<number> | null, w: Window | null): boolean {
  const wall = toWall(ts, zone);
  if (days !== null && !days.has(weekday(wall))) return false;
  return inWindow(wall.hh * 3600 + wall.mm * 60 + wall.ss + wall.frac, w);
}

function nextOpening(ts: number, zone: string, days: Set<number> | null, w: Window | null): number | null {
  if (allowed(ts, zone, days, w)) return ts;
  const d0 = wallDate(ts, zone);
  const segments: [number, number | null][] =
    w === null ? [[0, null]] : w[0] < w[1] ? [[w[0], w[1]]] : [[0, w[1]], [w[0], null]];
  for (let i = 0; i < 9; i++) {
    const d = addDays(d0, i);
    if (days !== null && !days.has(weekday(d))) continue;
    for (const [a, b] of segments) {
      const segStart = fromWall(d, Math.floor(a / 3600), Math.floor((a % 3600) / 60), zone);
      const cand = Math.max(ts, segStart);
      if (b !== null && cand > fromWall(d, Math.floor(b / 3600), Math.floor((b % 3600) / 60), zone)) continue;
      if (allowed(cand, zone, days, w)) return cand;
    }
  }
  return null;
}

function nextInterval(
  s: Schedule,
  after: number,
  zone: string,
  start: number | null,
  until: number | null,
  days: Set<number> | null,
  w: Window | null,
): number | null {
  const [kind, n] = parseEvery(s.every)!;
  if (start === null) {
    const cand = kind === "s" ? after + n : wallTs(addMonthsNaive(naiveAt(after, zone), n), zone);
    const res = nextOpening(cand, zone, days, w);
    if (res === null || (until !== null && res > until)) return null;
    return res;
  }

  let slot: (k: number) => number;
  let indexAtOrAfter: (x: number) => number;
  if (kind === "s") {
    slot = (k) => start + k * n;
    indexAtOrAfter = (x) => (x <= start ? 0 : Math.ceil((x - start) / n));
  } else {
    const wallStart = naiveAt(start, zone);
    const ws = new Date(Math.floor(wallStart) * 1000);
    slot = (k) => wallTs(addMonthsNaive(wallStart, k * n), zone);
    indexAtOrAfter = (x) => {
      if (x <= start) return 0;
      const xw = toWall(x, zone);
      let k = Math.max(0, Math.floor(((xw.y - ws.getUTCFullYear()) * 12 + xw.m - (ws.getUTCMonth() + 1)) / n) - 1);
      while (slot(k) < x) k += 1;
      return k;
    };
  }
  let k = indexAtOrAfter(after);
  if (slot(k) <= after) k += 1;
  for (let i = 0; i < MAX_GRID_STEPS; i++) {
    const sl = slot(k);
    if (until !== null && sl > until) return null;
    if (allowed(sl, zone, days, w)) return sl;
    const opening = nextOpening(sl, zone, days, w);
    if (opening === null) return null;
    k = Math.max(k + 1, indexAtOrAfter(opening));
  }
  return null;
}

/** First slot strictly after epoch `after`, or null if it never fires again.
 *  Ignores `count`. Precondition: scheduleError(sch) === null and the type is
 *  repeating. */
export function nextFire(sch: Schedule, after: number, boxZone: string = localZone()): number | null {
  const zone = present(sch.timezone) && sch.timezone !== "" ? String(sch.timezone) : boxZone;
  const start = present(sch.start) ? parseIso(sch.start, zone) : null;
  const until = present(sch.until) ? parseIso(sch.until, zone) : null;
  const days = parseDays(sch.days) || null;
  if (sch.type === "interval") {
    const w = present(sch.window) ? parseWindow(sch.window) : null;
    return nextInterval(sch, after, zone, start, until, days, w);
  }
  return nextWall(sch, after, zone, start, until, days);
}

// ---------------------------------------------------------------------------
// App-facing entry points
// ---------------------------------------------------------------------------

/** Parse a duration string like "30m" / "2h" / "1d" / "45s" into seconds.
 *  Bare number = minutes. Null on malformed input or calendar months. */
export function parseDurationSecs(raw: unknown): number | null {
  const e = parseEvery(raw);
  return e !== null && e[0] === "s" ? e[1] : null;
}

/**
 * Epoch seconds of the next fire for the app's "Next" display. `referenceSecs`
 * is `.last ?? .anchored` (null when the scheduler hasn't seen the spec yet —
 * we then project from now). `runs` is the `.runs` sentinel; a spec whose
 * `count` is used up has no next fire. Null for malformed schedules, past
 * one_shots, and schedules that never fire again. A value in the past means
 * the slot is due and fires on the scheduler's next poll.
 */
export function computeNextFireAt(
  schedule: unknown,
  referenceSecs: number | null,
  nowSecs: number,
  runs = 0,
  boxZone: string = localZone(),
): number | null {
  if (scheduleError(schedule) !== null) return null;
  const sch = schedule as Schedule;
  if (sch.type === "one_shot") {
    if (typeof sch.at !== "string") return null;
    const ms = Date.parse(sch.at.trim());
    if (Number.isNaN(ms)) return null;
    const ts = Math.floor(ms / 1000);
    return ts <= nowSecs ? null : ts;
  }
  const count = parsePositiveInt(sch.count);
  if (count !== null && runs >= count) return null;
  return nextFire(sch, referenceSecs ?? nowSecs, boxZone);
}
